### PR TITLE
Using Package::Stash

### PR DESCRIPTION
**Pull request by yanick**
mostly an exercise in Yak shaving for the CPAN challenge. :-)

The biggest change is the use of Package::Stash to play with the function overloading and the such.

### CODE REVIEW

**Comment by DrHyde** [comment]
I like the look of this shaved yak! Unfortunately it has test failures. I thought it would be just something simple like adding Package::Stash and List::MoreUtils to the list of prereqs but alas it isn't.

**Comment by yanick** [comment]
Hmm... I'll have a look at the travis failures and see if I can pinpoint what I messed up...

**Comment by DrHyde** [comment]
Thanks!

**Comment by yanick** [comment]
Pleasure was all mine, good sir. ^.^

**Comment by DrHyde** [comment]
Unfortunately it introduces some problematical dependencies and has odd test failures on some older perls, so I'm reverting it. Hopefully I'll be able to cherry-pick at least some of the improvements though after doing that.

**Comment by yanick** [comment]
> Unfortunately it introduces some problematical dependencies

Which ones, out of curiosity?

> Hopefully I'll be able to cherry-pick at least some of the improvements

I think my commits were piecemealy enough to allow you to pick and choose. If not, feel free to ask me to rejuggle my stuff, and I'll do it gladly.

**Comment by DrHyde** [comment]
List::MoreUtils depends on XSLoader, the current version of which doesn't like early perl 5.8s, and earlier versions have bugs.

Package::Stash emits some just plain odd errors on early 5.8s that I couldn't replicate in a smaller chunk of code, so I suspect it's actually tickling a bug in perl itself (not clearing out a C variable or an overflow or something) that has since been fixed: when running the Sub::WrapPackages tests on early 5.8s Package::Stash spits out, eg, "Banana::Tree is not a module name ...". If you look at the Package::Stash source it looks like this might be related to that mysterious issue with $1 getting clobbered. But not only can't I replicate it in a smaller bit of code, I can't even reliably replicate it on all my machines - it blows up on Linux/ARM and OS X/Intel, but not Linux/Intel. Weird.

But yes, I did manage to pick out the bits that didn't rely on those modules, and they're in the version that I pushed out to the CPAN a few days ago. Thanks for your contribution!

**Comment by yanick** [comment]
> List::MoreUtils depends on XSLoader, the current version of which doesn't like early perl 5.8s, and earlier versions have bugs.

Aaaah, I see. And yeah, "early 5.8" indeed sounds like some very vintage versions. :-)

> I did manage to pick out the bits that didn't rely on those modules

Beautiful. ^.^

**Pull request merged**
